CREATE TABLE IF NOT EXISTS urls (
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    original_url    TEXT NOT NULL,
    short_code      TEXT NOT NULL,
    created_at      TIMESTAMPTZ,
    hit_count       BIGINT DEFAULT 0,
    expiration_date TIMESTAMPTZ,
    CONSTRAINT uni_urls_short_code UNIQUE (short_code)
);
